### ISSUE TITLE
make异常。

### ISSUE THREAD

**Issue by MarsYoung** [session-replay-tools/intercept#2]
objs/src/communication/tc_socket.o: In function `tc_pcap_open':
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:14: undefined reference to `pcap_create'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:20: undefined reference to `pcap_set_snaplen'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:22: undefined reference to `pcap_statustostr'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:27: undefined reference to `pcap_set_promisc'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:34: undefined reference to `pcap_set_timeout'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:36: undefined reference to `pcap_statustostr'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:29: undefined reference to `pcap_statustostr'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:41: undefined reference to `pcap_set_buffer_size'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:50: undefined reference to `pcap_activate'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:43: undefined reference to `pcap_statustostr'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:57: undefined reference to `pcap_statustostr'
/opt/tcpcopy/intercept-1.0.0/src/communication/tc_socket.c:52: undefined reference to `pcap_statustostr'

找资料，发现可能是少了相关的库，所以安装了libpcap和libpcap-devel，但是还是不行。。

**Comment by wangbin579** [comment]
这些就是libpcap开发库的函数，可能路径没有找到吧。

**Comment by wangbin579** [comment]
configure的结果输出来吧

**Comment by MarsYoung** [comment]
lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 5.10

**Comment by MarsYoung** [comment]
intercept-1.0.0]# ./configure 
checking for OS
 + Linux 2.6 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.1.2 20080704 (Red Hat 4.1.2-54)
checking for gcc -pipe switch ... found
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for unistd.h ... found
checking for limits.h ... found
checking for inttypes.h ... found
checking for pcap.h ... found
checking for Linux specific features
checking for F_READAHEAD ... not found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for statfs() ... not found
checking for SO_SETFIB ... not found
checking for SO_ACCEPTFILTER ... not found
checking for TCP_DEFER_ACCEPT ... found
checking for TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT ... found
checking for TCP_INFO ... not found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 4 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for pread() ... found
checking for pwrite() ... found
checking for posix_memalign() ... found
checking for memalign() ... found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
creating objs/Makefile

Configuration summary

  intercept path prefix: "/usr/local/intercept"
  intercept binary file: "/usr/local/intercept/sbin/intercept"
  intercept configuration prefix: "/usr/local"
  intercept configuration file: "/usr/local/intercept/"
  intercept pid file: "/usr/local/intercept/logs/intercept.pid"
  intercept error log file: "/usr/local/intercept/logs/error_intercept.log"

**Comment by wangbin579** [comment]
最新版本，configure是有这么一行输出的：
checking for pcap_create()

可能是下载了比较老的release版本，直接用git clone下载吧

**Comment by wangbin579** [comment]
release 1.0.0已经更新到最新版本，也可以从那下载，但不保证每个时候都是最新版本
