### ISSUE TITLE
在主机只有一块网卡的时候是不是流量镜像不成功

### ISSUE THREAD

**Issue by xiaofenyang** [session-replay-tools/intercept#6]
我想问一下，我的主机只有一个网卡，是不是无法使用您的mirror代码。
同时tcpcopy，我看是支持只有一个网卡的，为什么mirror与tcpcopy的实现机制还不一致。

**Comment by lazio579** [comment]
没有这个硬性要求的。
具体失败原因，需要抓包分析的
